version: '2'

services:
    elasticsearch:
        build:
            context: ./elasticsearch
        ports:
            - "127.0.0.1:9200:9200"
        volumes:
            - ./config:/usr/share/elasticsearch/config
            - esdata:/usr/share/elasticsearch/data
        networks:
            - back
    kibana:
        build:
            context: ./kibana
        ports:
            - "127.0.0.1:5601:5601"
        volumes:
            - ./kibana/config:/opt/kibana/config/
        networks:
            - back

networks:
    back:

volumes:
    esdata: